fix(INJI-262):pinned VC's audit logs are missing
tw-mosip/inji pull request #108
Opened 2023-08-18 07:36 UTC by srikanth716

2023-08-18 10:03 UTC, vharsh commented on machines/vcItem.ts
> +            }),
IMO, the ticket states that the **audit logs** of the specifically selected VC should be shown and not the action of logging the VC being pinned & unpinned. Am I missing a discussion, if so please update the Jira ticket with the newer description.

2023-08-22 10:39 UTC, vharsh commented
@srikanth716 Please attach screenshots here and in Jira ticket

2023-08-23 06:34 UTC, swatigoel requested changes

2023-08-23 06:34 UTC, swatigoel commented on screens/Home/MyVcs/HistoryTab.tsx
> +            if (activity._vcKey.split(':')[3] == props.vcKey.split(':')[3]) {
extract it as variable and the use it for readibility.

2023-08-23 06:36 UTC, swatigoel commented
We could directly revert the commit `31b88dab1e5ad25ff0f139a456e562a2d1101ed8` to avoid any new bug because of changes.
We can take care of this in future

2023-08-23 11:43 UTC, swatigoel requested changes

2023-08-23 11:43 UTC, swatigoel commented on shared/constants.ts
> +export const isVcKeyMatch = (vckey: string, CompareVckey: string) => {
```
export const isSameVC = (vcKey: string, pinnedVcKey: string) => {
const requestId = vcKey.split(':')[3];
const pinnedRequestId = pinnedVcKey.split(':')[3];

return requestId === pinnedRequestId;
}
```

2023-08-23 11:43 UTC, swatigoel commented on screens/Home/MyVcs/HistoryTab.tsx
> +            const vcKeyMatch = isVcKeyMatch(activity._vcKey, props.vcKey);
isSameVC(activity._vcKey, props.vcKey)

2023-08-23 12:04 UTC, merged